(maint) Remove spaces in filenames
lingua-pupuli/docs pull request #51
Opened 2021-01-30 18:20 UTC by jpogran

2021-01-31 13:26 UTC, glennsarti requested changes

2021-01-31 13:26 UTC, glennsarti commented on vscode/content/en/docs/experience-a-problem.md
> +### 1. File an issue on our [Issues Page](https://github.com/puppetlabs/puppet-VS Code/issues)
nope.

2021-01-31 16:42 UTC, jpogran commented on vscode/content/en/docs/experience-a-problem.md
> +### 1. File an issue on our [Issues Page](https://github.com/puppetlabs/puppet-VS Code/issues)
good catch!

2021-02-01 00:36 UTC, glennsarti approved these changes

2021-02-01 18:32 UTC, merged